obsidian_entrypoint_path_str: music/_all_of_Music.md
toggles:
    no_clean: false
    process_all: true
    features:
        side_pane:
            left_pane:
                enabled: false
            right_pane:
                enabled: false
site_name: 'music'
html_url_prefix: '/Music'
